name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker buildx build --tag ${{secrets.DOCKER_HUB_USERNAME}}/yeungjin-global-test .
      
    - uses: actions/checkout@v3
    - name: Build the nginx Docker image
      run: docker buildx build --tag ${{secrets.DOCKER_HUB_USERNAME}}/yeungjin-global-test-nginx -f ./Dockerfile.nginx .
    
    - name: Docker login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_TOKEN}}

    - name: Push to Docker Hub
      env:
        REPO: yeungjin-global-test
      run: 
        docker push ${{secrets.DOCKER_HUB_USERNAME}}/$REPO

    - name: Push to Docker Hub (nginx)
      env:
        NGINX_REPO: yeungjin-global-test-nginx
      run: 
        docker push ${{secrets.DOCKER_HUB_USERNAME}}/$NGINX_REPO
  
    - name: Docker compose up in EC2
      uses: appleboy/ssh-action@v1.0.0
      with: 
        host: ${{secrets.EC2_HOST}}
        username: ${{secrets.EC2_USERNAME}}
        key: ${{secrets.EC2_KEY}}
        script_stop: true
        script: sh docker.sh #백그라운드 실행
