name: Move opened issue
on:
  issues:
    types:
      - opened
jobs:
  move-opened-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          project: Backend
          column: 예정
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
